runtime: php
env: flex

runtime_config:
    document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 1
    memory_gb: 2
    disk_size_gb: 10

env_variables:
    # Put production environment variables here.
    APP_ENV: production
    APP_NAME: "SamToni Profile"
    APP_KEY: base64:kaynfltmFM5KADih1At/dXJIWQBhZ6jTdlOMoThI9cc=
    APP_DEBUG: true
    APP_URL: http://localhost

    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: debug

    DB_CONNECTION: mysql
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_DATABASE: laravel
    DB_USERNAME: root
    DB_PASSWORD:

    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: sync
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120

    MEMCACHED_HOST: 127.0.0.1

    REDIS_HOST: 127.0.0.1
    REDIS_PASSWORD: null
    REDIS_PORT: 6379

    MAIL_MAILER: smtp
    MAIL_HOST: mailhog
    MAIL_PORT: 1025
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: null
    MAIL_FROM_ADDRESS: "tonitegarsahidi@gmail.com"
    MAIL_FROM_NAME: "${APP_NAME}"

    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_DEFAULT_REGION: us-east-1
    AWS_BUCKET:
    AWS_USE_PATH_STYLE_ENDPOINT: false

    PUSHER_APP_ID:
    PUSHER_APP_KEY:
    PUSHER_APP_SECRET:
    PUSHER_APP_CLUSTER: mt1

    MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
