steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'sudo apt install -y php7.3 php7.3-common php7.3-opcache php7.3-mcrypt php7.3-cli php7.3-gd php7.3-curl php7.3-mysql php7.3-dom phpunit ']

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'composer install && gcloud config set app/cloud_build_timeout 3600 && gcloud app deploy -q --promote -v=$BUILD_ID --project=$PROJECT_ID']

timeout: '3600s'
